#!/usr/bin/env python
import argparse

import IPython
from IPython.config.loader import Config
from IPython.frontend.terminal.embed import InteractiveShellEmbed

import ipymongo

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        'addr',
        default='mongodb://localhost:27017/test',
        nargs='?')
    options = parser.parse_args()
    argv = [ '--ext', 'ipymongo' ]
    shell = InteractiveShellEmbed(user_ns={})
    ipymongo.default_uri = ipymongo.set_uri(options.addr)
    shell.extension_manager.load_extension('ipymongo')
    shell()

if __name__ == '__main__':
    main()
